#!/bin/bash
echo -e "\nTurtle Firewall 2.1 - Blacklist";
echo -e "Copyright (c) 2001-2023 Andrea Frigido\n";

grep -E 'blacklist_feature.*="on"|="on".*blacklist_feature' /etc/turtlefirewall/fw.xml > /dev/null
if [ $? = 0 ]
 then

Help () {
 echo "Usage :  turtleblacklist [OPTION]"
 echo " "
 echo "  -v, --verify"
 echo "     verify ipset blacklist exists and create if not"
 echo " "
 echo "  -f, --flush"
 echo "     flush ipset blacklist"
 echo " "
 echo "  -c, --consolidate"
 echo "     consolidate blacklist.dat and whitelist.dat"
 echo " "
 echo "  -i, --import"
 echo "     import blacklist.dat into ipset blacklist"
 echo " "
 echo "  -a, --all"
 echo "     do verify, flush, consolidate and import"
 echo " "
 exit 0
}

Verify () {
echo -e "Verify : \c"
ipset -n list blacklist > /dev/null 2>&1
if [ $? = 0 ]
 then
  echo -e "OK"
 else
  ipset create blacklist hash:ip hashsize 16777216 maxelem 16777216
  if [ $? = 0 ]
   then
    echo -e "CREATED"
  else
    echo -e "FAIL"
  fi
fi
}

Flush () {
echo -e "Flush : \c"
ipset flush blacklist > /dev/null 2>&1
 if [ $? = 0 ]
  then
   echo -e "OK"
 else
   echo -e "FAIL"
 fi
}

Consolidate () {
echo -e "Consolidate : \c"
 [ -s /etc/turtlefirewall/whitelist.dat ] || echo "127.0.0.1" > /etc/turtlefirewall/whitelist.dat
 chmod 600 /etc/turtlefirewall/whitelist.dat
 [ -s /etc/turtlefirewall/blacklist.dat ] || touch /etc/turtlefirewall/blacklist.dat
 chmod 600 /etc/turtlefirewall/blacklist.dat

 while read whitelist
  do
   sed -i '/'$whitelist'/d' /etc/turtlefirewall/blacklist.dat
 done < /etc/turtlefirewall/whitelist.dat

echo -e "OK"
}

Import () {
if [ -t 1 ]; then echo -e "Import :  \c"; else echo -e "Import : \c"; fi
if [ -s /etc/turtlefirewall/blacklist.dat ]
 then
  i=1
  sp="/-\|"
  while read line
   do
    ipset add blacklist $line -q
    if [ -t 1 ]; then echo -en "\b${sp:i++%${#sp}:1}"; fi
  done < /etc/turtlefirewall/blacklist.dat
  if [ -t 1 ]; then echo -e "\bOK"; else echo -e "OK"; fi
 else
   echo -e "/etc/turtlefirewall/blacklist.dat empty"
fi
}

case $1 in
 -v|--verify) Verify;;
 -f|--flush) Flush;;
 -c|--consolidate) Consolidate;;
 -i|--import) Import;;
 -a|--all) Verify;Flush;Consolidate;Import;;
 *) Help;;
esac

else
 echo -e "Blacklist feature disabled in /etc/turtlefirewall/fw.xml"
fi

echo
