#!/bin/bash
#
# Enable Auto Update with :
# ln -sf /usr/lib/turtlefirewall/ip_blacklist /etc/cron.daily/ip_blacklist
#

echo -e "\nTurtle Firewall 2.3 - IP Blacklist";
echo -e "Copyright (c) 2001-2024 Andrea Frigido\n";

fw_file="/etc/turtlefirewall/fw.xml"

blacklist_file="/etc/turtlefirewall/ip_blacklist.dat"
never_blacklist_file="/etc/turtlefirewall/never_ip_blacklist.dat"

Help () {
 echo "Usage :  ip_blacklist [OPTION]"
 echo " "
 echo "  -I, --initialise"
 echo "     initialise blacklist firewall item"
 echo " "
 echo "  -f, --flush"
 echo "     flush blacklist firewall item"
 echo " "
 echo "  -d, --download"
 echo "     download blacklist file"
 echo " "
 echo "  -i, --import"
 echo "     import blacklist file into firewall item"
 echo " "
 echo "  -h, --help"
 echo "     this menu"
 echo " "
 echo "  -x, --exclude-download"
 echo "     do intialise, flush and import"
 echo " "
 exit 0
}

Initialise () {
echo -e "Initialise : \c"
ipset -n list ip_blacklist > /dev/null 2>&1
if [ $? = 0 ]
 then
  echo -e "OK"
 else
  ipset create ip_blacklist hash:ip hashsize 16777216 maxelem 16777216
  if [ $? = 0 ]
   then
    echo -e "CREATED"
  else
    echo -e "FAIL"
  fi
fi
}

Flush () {
echo -e "Flush : \c"
ipset flush ip_blacklist > /dev/null 2>&1
 if [ $? = 0 ]
  then
   echo -e "OK"
 else
   echo -e "FAIL"
 fi
}

Download () {
echo -e "Download : \c"
systemctl is-enabled turtlefirewall > /dev/null 2>&1
if [ $? = 0 ]
 then
  result="1"
  wget -q -O - https://sslbl.abuse.ch/blacklist/sslipblacklist.txt \
   | dos2unix \
   | awk '(!/^#/ && $1~/^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$/){print $1}' \
   > $blacklist_file
  [ $? = 0 ] && result=0
  wget -q -O - https://feodotracker.abuse.ch/downloads/ipblocklist_recommended.txt \
   | dos2unix \
   | awk '(!/^#/ && $1~/^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$/){print $1}' \
   >> $blacklist_file
  [ $? = 0 ] && result=0
  wget -q -O - https://lists.blocklist.de/lists/all.txt \
   | dos2unix \
   | awk '(!/^#/ && $1~/^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$/){print $1}' \
   >> $blacklist_file
  [ $? = 0 ] && result=0
  if [ $result = 0 ]
   then
    echo -e "OK"
  else
    echo -e "FAIL"
  fi
  sort -u $blacklist_file -o $blacklist_file
  chmod 600 $blacklist_file
else
  echo -e "turtlefirewall not enabled"
  echo
  exit 1
fi
}

Import () {
if [ -t 1 ]; then echo -e "Import :  \c"; else echo -e "Import : \c"; fi
if [ -s $blacklist_file ]
 then

  # Ensure exclude
  if [ -s $never_blacklist_file ]
   then
    while read blacklist_exclude
    do
     sed -i "/^$blacklist_exclude$/d" $blacklist_file
    done < $never_blacklist_file
  fi

  count=`wc -l < $blacklist_file`
  i=1
  sp="/-\|"
  while read line
   do
    ipset add ip_blacklist $line -q
    if [ -t 1 ]; then echo -en "\b${sp:i++%${#sp}:1}"; fi
  done < $blacklist_file
  if [ -t 1 ]; then echo -e "\b$count"; else echo -e "$count"; fi
 else
   echo -e "$blacklist_file empty"
fi
}

case $1 in
 -I|--initialise) Initialise;;
 -f|--flush) Flush;;
 -d|--download) Download;;
 -i|--import) Import;;
 -h|--help) Help;;
 -x|--exclude-download) Initialise;Flush;Import;;
 *) Initialise;Flush;Download;Import;;
esac

echo
