#!/bin/bash
echo -e "\nTurtle Firewall 2.2 - IP Blacklist";
echo -e "Copyright (c) 2001-2023 Andrea Frigido\n";

fw_file="/etc/turtlefirewall/fw.xml"

grep -E 'drop_ip_blacklist.*="on"|="on".*drop_ip_blacklist' $fw_file > /dev/null
if [ $? = 0 ]
 then

blacklist_file="/etc/turtlefirewall/ip_blacklist.dat"

Help () {
 echo "Usage :  ip_blacklist [OPTION]"
 echo " "
 echo "  -I, --initialise"
 echo "     initialise blacklist firewall item"
 echo " "
 echo "  -f, --flush"
 echo "     flush blacklist firewall item"
 echo " "
 echo "  -d, --download"
 echo "     download blacklist file"
 echo " "
 echo "  -i, --import"
 echo "     import blacklist file into firewall item"
 echo " "
 echo "  -h, --help"
 echo "     this menu"
 echo " "
 echo "  -x, --exclude-download"
 echo "     do intialise, flush and import"
 echo " "
 exit 0
}

Initialise () {
echo -e "Initialise : \c"
ipset -n list drop_ip_blacklist > /dev/null 2>&1
if [ $? = 0 ]
 then
  echo -e "OK"
 else
  ipset create drop_ip_blacklist hash:ip hashsize 16777216 maxelem 16777216
  if [ $? = 0 ]
   then
    echo -e "CREATED"
  else
    echo -e "FAIL"
  fi
fi
}

Flush () {
echo -e "Flush : \c"
ipset flush drop_ip_blacklist > /dev/null 2>&1
 if [ $? = 0 ]
  then
   echo -e "OK"
 else
   echo -e "FAIL"
 fi
}

Download () {
echo -e "Download : \c"
systemctl is-enabled turtlefirewall > /dev/null 2>&1
if [ $? = 0 ]
 then
   result="1"
   wget -q -O - https://sslbl.abuse.ch/blacklist/sslipblacklist.txt \
    | dos2unix \
    | awk '(!/^#/ && $1~/^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$/){print $1}' \
    | sort -u \
    > $blacklist_file
   [ $? = 0 ] && result=0
   wget -q -O - https://feodotracker.abuse.ch/downloads/ipblocklist_recommended.txt \
    | dos2unix \
    | awk '(!/^#/ && $1~/^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$/){print $1}' \
    | sort -u \
    >> $blacklist_file
   [ $? = 0 ] && result=0
   wget -q -O - https://lists.blocklist.de/lists/all.txt \
    | dos2unix \
    | awk '(!/^#/ && $1~/^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$/){print $1}' \
    | sort -u \
    >> $blacklist_file
   [ $? = 0 ] && result=0
   if [ $result = 0 ]
    then
     echo -e "OK"
   else
     echo -e "FAIL"
   fi
  chmod 600 $blacklist_file
else
  echo -e "turtlefirewall not enabled"
  echo
  exit 1
fi
}

Import () {
if [ -t 1 ]; then echo -e "Import :  \c"; else echo -e "Import : \c"; fi
if [ -s $blacklist_file ]
 then
  count=`wc -l < $blacklist_file`
  i=1
  sp="/-\|"
  while read line
   do
    ipset add drop_ip_blacklist $line -q
    if [ -t 1 ]; then echo -en "\b${sp:i++%${#sp}:1}"; fi
  done < $blacklist_file
  if [ -t 1 ]; then echo -e "\b$count"; else echo -e "$count"; fi
 else
   echo -e "$blacklist_file empty"
fi
}

case $1 in
 -I|--initialise) Initialise;;
 -f|--flush) Flush;;
 -d|--download) Download;;
 -i|--import) Import;;
 -h|--help) Help;;
 -x|--exclude-download) Initialise;Flush;Import;;
 *) Initialise;Flush;Download;Import;;
esac

else
 echo -e "drop_ip_blacklist disabled in $fw_file"
fi

echo
