#!/usr/bin/env bash
[ ! -d /usr/share/xt_geoip ] && mkdir -p /usr/share/xt_geoip
cd /var/tmp
/usr/libexec/xtables-addons/xt_geoip_dl
/usr/libexec/xtables-addons/xt_geoip_build -s
rm -rf dbip-country-lite.csv
